### ISSUE TITLE
Release of checkpoints

### ISSUE THREAD

**Issue by SimJeg** [zylye123/CARes-UNet#2]
Hello,

Do you have any plan to release checkpoints of the models you trained ? I believe it would be very useful for the community and make life easier for benchmarks :) thank you for your work !

**Comment by Oleki-xxh** [comment]
Hi,

Thank you for your suggestion. We havd updated the readme file and release the supervised checkpoint trained on COVID-SemiSeg Dataset for test demo. You can download it here “https://drive.google.com/file/d/1jv4OCiJGfWGRN3qdecJ4GXgH8uGdAkAw/view?usp=sharing”. Checkpoints trained on other datasets will be released soon.

Sorry to reply so late. Hopefully it will help you.

**Comment by SimJeg** [comment]
Hello, 

I was able to run the model on new slices. Is there an optimal resolution and size to run the model ? From the code the size seems to be 256 pixels, for the resolution is it variable ? (e.g. 1.8mm / voxel). Also should we better crop images around the lungs ?

**Comment by zylye123** [comment]
Hi,

Thank you for your question. If you want to use the checkpoint, the resolution and size should be **strictly** 256 * 256. If you prefer to use your own slices, you should at least resize or crop them first.

As for cropping around the lungs, we suggest that you could crop them like the _Original Image_ from _4.3 Experiment Results_ in readme file, since the checkpoint was trained with these images. I assume that it would achieve better performance if you could finetune the pre-trained model first before you use it.

We are delighted to discuss about the related problems with you. Hopefully it would help you :)
